services:
  db:
    image: postgres
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U XgkJUcqxEw -d event_ticket_fastapi"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - event_ticket_fastapi_db_data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 8001:80
    env_file:
      - .env
    volumes:
      - event_ticket_fastapi_pgadmin_data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    image: event_ticket_fastapi:dev
    ports:
      - 8000:8000
    # environment:
    #   - DATABASE_URL=postgresql://postgres:postgres@db:5432/cleanfastapi
    volumes:
      - ./:/usr/src/app
    user: "${UID}:${GID}"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  event_ticket_fastapi_db_data:
  event_ticket_fastapi_pgadmin_data:
