"""Added FK to Payment Status in Transaction

Revision ID: 1b9a13f2d6a1
Revises: f1d15f46ea81
Create Date: 2025-05-03 10:05:11.087078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b9a13f2d6a1'
down_revision: Union[str, None] = 'f1d15f46ea81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payment_status_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'data_lookups', ['payment_status_id'], ['id'])
    op.drop_column('transactions', 'payment_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payment_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'payment_status_id')
    # ### end Alembic commands ###
