"""update Reservation status to link with DataLookup

Revision ID: 28393b19762d
Revises: 708155abef60
Create Date: 2025-04-16 15:53:14.425707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28393b19762d'
down_revision: Union[str, None] = '708155abef60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('status_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'reservations', 'data_lookups', ['status_id'], ['id'])
    op.drop_column('reservations', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_column('reservations', 'status_id')
    # ### end Alembic commands ###
