"""create new tables

Revision ID: 58ece6cd3329
Revises: dcc05abf0f9b
Create Date: 2025-04-16 14:05:10.018963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ece6cd3329'
down_revision: Union[str, None] = 'dcc05abf0f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_lookups',
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('remark', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'value')
    )
    op.drop_constraint('unq_event_seat_reservation', 'reservations', type_='unique')
    op.drop_constraint('reservations_seat_id_fkey', 'reservations', type_='foreignkey')
    op.drop_column('reservations', 'seat_id')
    op.add_column('seats', sa.Column('status_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'seats', 'data_lookups', ['status_id'], ['id'])
    op.drop_column('seats', 'is_available')
    op.drop_column('tickets', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('seats', sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'seats', type_='foreignkey')
    op.drop_column('seats', 'status_id')
    op.add_column('reservations', sa.Column('seat_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('reservations_seat_id_fkey', 'reservations', 'seats', ['seat_id'], ['id'])
    op.create_unique_constraint('unq_event_seat_reservation', 'reservations', ['event_id', 'seat_id'])
    op.drop_table('data_lookups')
    # ### end Alembic commands ###
