"""Added account table

Revision ID: 597cccf00786
Revises: cecbd53b8466
Create Date: 2025-05-02 20:12:29.110176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '597cccf00786'
down_revision: Union[str, None] = 'cecbd53b8466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('reservation_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'tickets', 'reservations', ['reservation_id'], ['id'])
    op.add_column('transactions', sa.Column('reservation_id', sa.Uuid(), nullable=False))
    op.drop_constraint('transactions_ticket_id_transaction_date_key', 'transactions', type_='unique')
    op.create_unique_constraint(None, 'transactions', ['transaction_date'])
    op.drop_constraint('transactions_ticket_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'reservations', ['reservation_id'], ['id'])
    op.drop_column('transactions', 'ticket_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('ticket_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_ticket_id_fkey', 'transactions', 'tickets', ['ticket_id'], ['id'])
    op.drop_constraint(None, 'transactions', type_='unique')
    op.create_unique_constraint('transactions_ticket_id_transaction_date_key', 'transactions', ['ticket_id', 'transaction_date'])
    op.drop_column('transactions', 'reservation_id')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'reservation_id')
    # ### end Alembic commands ###
