"""update Ticket status to likn with DataLookup

Revision ID: 708155abef60
Revises: c60ebb326ba7
Create Date: 2025-04-16 15:43:21.229411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708155abef60'
down_revision: Union[str, None] = 'c60ebb326ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('status_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'tickets', 'data_lookups', ['status_id'], ['id'])
    op.drop_column('tickets', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'status_id')
    # ### end Alembic commands ###
