"""update seat FK to make nullable

Revision ID: c60ebb326ba7
Revises: 58ece6cd3329
Create Date: 2025-04-16 15:34:25.339716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c60ebb326ba7'
down_revision: Union[str, None] = '58ece6cd3329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'seat_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'seat_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
